### ISSUE TITLE
It is Stuck on indexWriter.Dispose() 101,000 documents in the demo.

### ISSUE THREAD

**Issue by sheryever** [TimMahyInfoSupport/LuceneNetSqlDirectory#3]
@MahyTim I am trying to write the same kind of lucene directory for LiteDB but LuceneNetSqlDirectory has stuck on calling `indexWriter.Displose()` after indexing 101,000 documents in the demo application.

Have you face the same kind of issue?

On my side it is having same behavior on 10,000 documents.

**Comment by MahyTim** [comment]
I commited yesterday what should be a fix for your problem :) now I just need to start using pull requests to make it more clear :)

**Comment by sheryever** [comment]
Great thanks 👍.
I have downloaded the code and will check now :)

**Comment by MahyTim** [comment]
see latest commits

**Comment by sheryever** [comment]
Checking

**Comment by MahyTim** [comment]
Just improved the IndexInput & Output using a buffered approach and gained 250% increase in performance :) hoeray :)

**Comment by sheryever** [comment]
I just checked... it's great improvement... but on 10,000 document Sql client hangs and throwing timeout exception.

**Comment by sheryever** [comment]
I was reading the code of lucenenet, they have wrote bufferedIndex in SimpleFSDirectory and i think that is fast because of that.
